name: Build all
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ubuntu environment
        run: docker build --target builder_base -t belcarra_base --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Set up project source
        run: docker build --target builder_source -t belcarra_source --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Set up project dependencies
        run: docker build --target builder_depend -t belcarra_depend --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build AFL
        run: docker build --target builder_afl -t belcarra_afl --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build SymCC simple backend
        run: docker build --target builder_symcc_simple -t belcarra_symcc_simple --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build LLVM libcxx using SymCC simple backend
        run: docker build --target builder_symcc_libcxx -t belcarra_symcc_libcxx --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build SymCC Qsym backend
        run: docker build --target builder_symcc_qsym -t belcarra_symcc_qsym --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build SymLLVM
        run: docker build --target builder_symllvm -t belcarra_symllvm --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build SymRustC core
        run: docker build --target builder_symrustc -t belcarra_symrustc --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build SymRustC main
        run: docker build --target builder_symrustc_main -t belcarra_symrustc_main --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Set up Ubuntu/Rust environment
        run: docker build --target builder_base_rust -t belcarra_base_rust --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build LibAFL solving runtime
        run: docker build --target builder_libafl_solving -t belcarra_libafl_solving --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build LibAFL solving runtime main
        run: docker build --target builder_libafl_solving_main -t belcarra_libafl_solving_main --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build end user environment
        run: docker build --target builder_end_user -t belcarra_end_user --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

      - name: Build end user environment main
        run: docker build --target builder_end_user_main -t belcarra_end_user_main --build-arg SYMRUSTC_CI=yes --build-arg SYMRUSTC_VERBOSE=true --build-arg SYMRUSTC_BRANCH='main' --build-arg SYMRUSTC_DIR_COPY='examples' --build-arg SYMRUSTC_SKIP_FAIL=yes --build-arg SYMRUSTC_LIBAFL_EXAMPLE_SKIP_BUILD_TRACING=yes .

